env:
  browser: true
  node: true

settings:
  import/resolver:
    node:
      paths:
        - src
        - public
      extensions:
        - .js
        - .jsx
        - .ts
        - .tsx
        - .svg

rules:
  no-console: "off"   # Disable console warnings
  linebreak-style: 0   # Disable linebreak style errors
  no-plusplus: "off"   # Disable no-plusplus errors

extends:
  - eslint:recommended
  - plugin:import/recommended
  - plugin:@typescript-eslint/recommended
  - eslint-config-prettier