# Stage 1: Development
FROM node:16 AS development
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm install
COPY . ./
EXPOSE 5000
CMD ["npm", "run", "dev"]

# Stage 2: Production
FROM node:16 AS production
WORKDIR /app
COPY package.json package-lock.json ./
RUN npm install --production
COPY . ./
EXPOSE 5000
CMD ["npm", "start"]
